import CryptoKit
import Foundation
import ImageIO
import UniformTypeIdentifiers

/// Decides what NotchDeck keeps from a clipboard change, and what it never keeps. Pure functions,
/// so every rule is unit tested.
enum ClipboardCapture {
    /// Markers apps put on the clipboard for passwords, one-time codes and other content that
    /// clipboard tools must not keep (nspasteboard.org conventions and common app-specific ones).
    /// Seeing any of them, NotchDeck doesn't read the clipboard at all.
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]

    /// Password managers: their copies are never kept, even without a marker.
    static let alwaysExcludedBundleIDs: Set<String> = [
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
        "org.keepassxc.keepassxc",
        "com.sinew.Enpass-Desktop",
        "com.markmcguill.strongbox.mac",
        "com.proton.pass.electron",
    ]

    /// Longer text isn't kept (it would bloat the history file).
    static let maxTextLength = 100_000
    /// Formatting is kept only for small rich text; larger copies keep their plain text.
    static let maxRTFSize = 256 * 1024
    /// Larger images aren't kept.
    static let maxImageSize = 20 * 1024 * 1024

    /// Editors and terminals: text copied from them is shown as code.
    static let codeSourceBundleIDs: Set<String> = [
        "com.apple.dt.Xcode",
        "com.microsoft.VSCode",
        "com.todesktop.230313mzl4w4u92", // Cursor
        "dev.zed.Zed",
        "com.sublimetext.4",
        "com.panic.Nova",
        "com.barebones.bbedit",
        "com.apple.Terminal",
        "com.googlecode.iterm2",
        "com.mitchellh.ghostty",
        "dev.warp.Warp-Stable",
    ]

    /// What was read from the clipboard. Only the representations NotchDeck keeps are read.
    struct Snapshot: Equatable, Sendable {
        var fileURLs: [URL] = []
        var string: String?
        var rtf: Data?
        /// A URL put on the clipboard as a URL (not as text).
        var url: URL?
        var imageData: Data?
        var imageType: UTType?
        var color: ColorComponents?
    }

    enum Result: Equatable, Sendable {
        case entry(ClipboardContent, ClipboardKind)
        /// Image data, to be hashed, stored and thumbnailed off the main thread.
        case image(Data, UTType)
    }

    static func shouldIgnore(types: [String]) -> Bool {
        types.contains(where: ignoredTypes.contains)
    }

    static func isExcluded(_ bundleID: String?, userExcluded: Set<String>) -> Bool {
        guard let bundleID else { return false }
        return alwaysExcludedBundleIDs.contains(bundleID) || userExcluded.contains(bundleID)
    }

    /// What to keep from a snapshot: files, then text (as a color, link, code or text), then an image,
    /// then a URL. Whitespace-only and oversized copies are not kept.
    static func result(from snapshot: Snapshot, sourceBundleID: String?) -> Result? {
        if !snapshot.fileURLs.isEmpty {
            return .entry(.files(snapshot.fileURLs), .files)
        }
        if let string = snapshot.string {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, string.count <= maxTextLength else { return nil }
            if let color = ColorParser.parse(trimmed) {
                return .entry(.color(color, text: trimmed), .color)
            }
            if let url = webURL(in: trimmed) {
                return .entry(.link(url), .link)
            }
            let rtf = snapshot.rtf.flatMap { $0.count <= maxRTFSize ? $0 : nil }
            return .entry(.text(string, rtf: rtf), isCode(string, sourceBundleID: sourceBundleID) ? .code : .text)
        }
        if let data = snapshot.imageData, let type = snapshot.imageType, !data.isEmpty {
            return data.count <= maxImageSize ? .image(data, type) : nil
        }
        if let color = snapshot.color {
            return .entry(.color(color, text: ColorParser.hex(color)), .color)
        }
        if let url = snapshot.url, let link = webURL(in: url.absoluteString) {
            return .entry(.link(link), .link)
        }
        return nil
    }

    /// The text as a web link, if it is exactly one `http`/`https` URL.
    static func webURL(in text: String) -> URL? {
        guard !text.contains(where: \.isWhitespace),
              let url = URL(string: text),
              let scheme = url.scheme?.lowercased(), scheme == "https" || scheme == "http",
              url.host() != nil else { return nil }
        return url
    }

    /// Whether text looks like source code: copied from an editor or terminal, or several lines
    /// most of which end or start like code.
    static func isCode(_ text: String, sourceBundleID: String?) -> Bool {
        if let sourceBundleID,
           codeSourceBundleIDs.contains(sourceBundleID) || sourceBundleID.hasPrefix("com.jetbrains.") {
            return true
        }
        let lines = text.split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        guard lines.count >= 2 else { return false }
        let codeLike = lines.filter { line in
            line.hasSuffix(";") || line.hasSuffix("{") || line.hasSuffix("}") || line.hasSuffix(")")
                || line == "}" || codePrefixes.contains { line.hasPrefix($0) }
        }
        return Double(codeLike.count) / Double(lines.count) >= 0.5
    }

    private static let codePrefixes = [
        "func ", "let ", "var ", "const ", "import ", "def ", "class ", "struct ", "enum ", "return ",
        "if (", "for (", "while (", "#include", "#import", "public ", "private ", "fn ", "//", "/*",
        "<div", "</", "SELECT ",
    ]

    /// A digest identifying the content, so copying the same thing twice keeps one entry.
    static func fingerprint(of content: ClipboardContent) -> String {
        switch content {
        case .text(let text, _): digest("text:" + text)
        case .link(let url): digest("link:" + url.absoluteString)
        case .color(_, let text): digest("color:" + text.lowercased())
        case .files(let urls): digest("files:" + urls.map(\.path).joined(separator: "\n"))
        // Images are fingerprinted from their data when captured (`ClipboardImageProcessing`).
        case .image(let image): "image-file:" + image.fileName
        }
    }

    static func digest(_ string: String) -> String {
        digest(Data(string.utf8))
    }

    static func digest(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}

/// Image work for the clipboard, done off the main thread: a digest for deduplication, the size,
/// and a small thumbnail so the notch never decodes the full image.
enum ClipboardImageProcessing {
    static let thumbnailPixelSize = 96

    struct Prepared: Equatable, Sendable {
        var fingerprint: String
        var pixelWidth: Int
        var pixelHeight: Int
        var thumbnail: Data?
    }

    nonisolated static func prepare(_ data: Data) -> Prepared? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int else { return nil }
        return Prepared(
            fingerprint: "image:" + ClipboardCapture.digest(data),
            pixelWidth: width,
            pixelHeight: height,
            thumbnail: thumbnail(from: source)
        )
    }

    nonisolated static func thumbnail(at url: URL) -> Data? {
        CGImageSourceCreateWithURL(url as CFURL, nil).flatMap(thumbnail(from:))
    }

    /// A PNG at most `thumbnailPixelSize` on its longer side, decoded at that size.
    nonisolated static func thumbnail(from source: CGImageSource) -> Data? {
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: thumbnailPixelSize,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(output, UTType.png.identifier as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        return CGImageDestinationFinalize(destination) ? output as Data : nil
    }
}

/// Recognizes colors copied as text: `#RGB`, `#RGBA`, `#RRGGBB`, `#RRGGBBAA`, `rgb(…)` and `rgba(…)`.
enum ColorParser {
    static func parse(_ text: String) -> ColorComponents? {
        let text = text.trimmingCharacters(in: .whitespaces)
        if text.hasPrefix("#") {
            return hexColor(String(text.dropFirst()))
        }
        let lower = text.lowercased()
        for prefix in ["rgba(", "rgb("] where lower.hasPrefix(prefix) && lower.hasSuffix(")") {
            return rgbColor(String(lower.dropFirst(prefix.count).dropLast()))
        }
        return nil
    }

    /// "#RRGGBB", or "#RRGGBBAA" when not opaque.
    static func hex(_ color: ColorComponents) -> String {
        func byte(_ value: Double) -> String { String(format: "%02X", Int((value * 255).rounded())) }
        let rgb = "#" + byte(color.red) + byte(color.green) + byte(color.blue)
        return color.alpha < 1 ? rgb + byte(color.alpha) : rgb
    }

    private static func hexColor(_ digits: String) -> ColorComponents? {
        guard [3, 4, 6, 8].contains(digits.count), digits.allSatisfy(\.isHexDigit) else { return nil }
        let expanded = digits.count <= 4 ? digits.map { "\($0)\($0)" }.joined() : digits
        var values: [Double] = []
        var index = expanded.startIndex
        while index < expanded.endIndex {
            let next = expanded.index(index, offsetBy: 2)
            guard let byte = UInt8(expanded[index..<next], radix: 16) else { return nil }
            values.append(Double(byte) / 255)
            index = next
        }
        return ColorComponents(red: values[0], green: values[1], blue: values[2], alpha: values.count > 3 ? values[3] : 1)
    }

    /// "255, 136, 0", "255 136 0 / 50%" or "255, 136, 0, 0.5".
    private static func rgbColor(_ arguments: String) -> ColorComponents? {
        let parts = arguments
            .replacingOccurrences(of: "/", with: " ")
            .replacingOccurrences(of: ",", with: " ")
            .split(whereSeparator: \.isWhitespace)
            .map(String.init)
        guard parts.count == 3 || parts.count == 4 else { return nil }
        var channels: [Double] = []
        for part in parts.prefix(3) {
            guard let value = channel(part, scale: 255) else { return nil }
            channels.append(value)
        }
        let alpha = parts.count == 4 ? channel(parts[3], scale: 1) : 1
        guard let alpha else { return nil }
        return ColorComponents(red: channels[0], green: channels[1], blue: channels[2], alpha: alpha)
    }

    /// A number in `0...scale`, or a percentage.
    private static func channel(_ text: String, scale: Double) -> Double? {
        if text.hasSuffix("%") {
            guard let percent = Double(text.dropLast()), (0...100).contains(percent) else { return nil }
            return percent / 100
        }
        guard let value = Double(text), (0...scale).contains(value) else { return nil }
        return value / scale
    }
}
